project_name: vint-depth-finetune
run_name: vint-depth-scand-run-1

# training setup
use_wandb: True
train: True
batch_size: 128 # Lowered batch size slightly, as the model is a bit larger
epochs: 50 # You might not need as many epochs for fine-tuning
gpu_ids: [0]
num_workers: 12
lr: 1e-4 # A slightly lower learning rate is often good for fine-tuning
optimizer: adamw
clipping: False
max_norm: 1.
scheduler: "cosine"
warmup: True 
warmup_epochs: 4
seed: 0

# --- Key changes for DepthViNT ---
# Set the model type to load your new DepthViNT model
model_type: vint_depth 

# Path to the original vint.pth file to start fine-tuning from
# This is used ONLY when starting a new run (not resuming)
finetune_from_vint_pth: "/home/airlab/vint_fuse2/visualnav-transformer/deployment/model_weights/vint.pth"

# Weight for the FuSe-inspired contrastive loss
contrastive_weight: 0.1

# model params (these should match the original ViNT model)
obs_encoder: "efficientnet-b0"
obs_encoding_size: 512
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
late_fusion: False

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 5

# distance bounds (remains the same)
distance:
  min_dist_cat: 0
  max_dist_cat: 20
action:
  min_dist_cat: 0
  max_dist_cat: 10
close_far_threshold: 10

# action output params
len_traj_pred: 5
learn_angle: True

# dataset specific parameters
image_size: [85, 64] # width, height
goal_type: "image"

# --- Enable your SCAND dataset ---
datasets:
  scand:
    data_folder: /home/airlab/vint_fuse2/SCAND # Make sure this path is correct
    train: /home/airlab/vint_fuse2/SCAND/train/ # Make sure this path is correct
    test: /home/airlab/vint_fuse2/SCAND/test/ # Make sure this path is correct
    end_slack: 0
    goals_per_obs: 1
    negative_mining: True

  # --- Other datasets are commented out to focus training ---
  # recon:
  #   data_folder: /path/to/vint_dataset/recon
  #   train: /path/to/data_splits/recon/train/ 
  #   test: /path/to/data_splits/recon/test/ 
  #   end_slack: 3 
  #   goals_per_obs: 1 
  #   negative_mining: True 
  # go_stanford:
  #   data_folder: /path/to/vint_dataset/go_stanford_cropped 
  #   train: /path/to/data_splits/go_stanford/train/
  #   test: /path/to/data_splits/go_stanford/test/
  #   end_slack: 0
  #   goals_per_obs: 2 
  #   negative_mining: True

# logging stuff
print_log_freq: 100 
image_log_freq: 1000
num_images_log: 8
eval_fraction: 0.25
wandb_log_freq: 10
eval_freq: 1